version: '3'
services:
  frontend:
    image: chokshi/frontend-image:latest
    restart: always
    ports:
      - '3000:3000'
  backend:
    image: chokshi/backend-image:latest
    restart: always
    ports:
      - '3001:3001'
    environment:
      - JWT_SECRET=SDNCN23423TN394UFKND
      - MONGO_URL=mongodb+srv://charan03:030904@clusterecoverse.xxoya0d.mongodb.net/ecoverse
      - jwt_token=dhfmharnca394020
